//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EmpData
    {

        public int empId { get; set; }
        [DisplayName("生日")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> empBirth { get; set; }
        [DisplayName("年齡")]
        public Nullable<int> empAge { get; set; }
        [DisplayName("姓名")]
        public string empName { get; set; }

    }
    public partial class HtmlStreamData
    {
        public IEnumerable<WebTest_MVC.Models.EmpData> empDatas { get; set; }
        public WebTest_MVC.Models.EmpData empMem { get; set; }        
    }
}
